package com.lexor.lexer;

public enum TokenType {
    SCRIPT, AREA, START, END, DECLARE, PRINT, SCAN,
    
    INT, FLOAT, CHAR, BOOL,

    IDENTIFIER, STRING, NUMBER, BOOL_LITERAL,
    
    AND, OR, NOT,
    
    EQUAL, AMPERSAND, COLON, DOLLAR, COMMA, MINUS, PLUS, STAR, SLASH, PERCENT,
    
    LEFT_PAREN, RIGHT_PAREN, 
    
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, EQUAL_EQUAL, LESS_GREATER,
    
    EOF
}